name: Build website as docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/q-swiper/map-generator:${{ env.IMAGE_VERSION }}
            ghcr.io/q-swiper/map-generator:latest
          build-args: |
            VERSION=alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8

  trigger-deployment:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger image update in Calfur/calfur-dev
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_ACTIONS_TRIGGER }}
          repository: Calfur/calfur-dev
          event-type: new-q-swiper-image
          client-payload: '{"image_version": "${{ env.IMAGE_VERSION }}"}'
